### ISSUE TITLE
Please take my money

### ISSUE THREAD

**Issue by anton-isidore** [VincentAudibert/CanIDrive#121]
I just want to thank you for this great app. I have used it in many jurisdictions (Spain, Poland, Austria, ...). I absolutely love it. I am a big beer lover and it's great to be able to taste a new beer and know when I can drive.

App is minimalist, clean, pure and does all I need.

One time in Czechia, I was even pulled over by police just on the edge time of the soberness. And it was OK. (Czechia has strict 0 tolerance.) But I created custom drinks with exact % for that case to make is precise.

Ok, so now, where I can send you money?💰

Please share your LN address or if you are not familiar with Bitcoin and Lightning Network contact me at anton.isidore@protonmail.com 🤟

**Comment by VincentAudibert** [comment]
Well, thanks a lot for this supporting issue, it is in itself a kind reward ! :pray: 

Regarding the money, I won’t take any, no offence :slightly_smiling_face: . This is now an old learning side-project and I cannot dare say it is maintained :sweat: . It keeps livings its life as is on the Playstore, pending enough personal time to allocate on updating it.

I’m very glad you found such value in it ! :+1:

**Comment by anton-isidore** [comment]
Ok. :)

Btw how do is the list of alcohol limits maintained. 

I can imagine that law can change and then it may be a big problem.

I travel a bit so sometimes I like to enjoy the benevolence of different jurisdictions :)

Is it hardcoded? What is the primary source for this?

**Comment by VincentAudibert** [comment]
Yes, drive law data is [hardcoded here](https://github.com/VincentAudibert/CanIDrive/blob/master/app/src/main/java/com/vaudibert/canidrive/ui/repository/DriveLaws.kt), as it was much simpler than relying on a backend for providing data. The idea was also to publish the app on the Fdroid store, so no proprietary dependency.

This means that law data cannot be updated beside a full app update, though I found a lot of these regulations were quite stable since driving got normalized in the concerned countries.

According to the comment in the file (didn't remember 😅 ), I used mainly [https://en.wikipedia.org/wiki/Drunk_driving_law_by_country](https://en.wikipedia.org/wiki/Drunk_driving_law_by_country).

**Comment by anton-isidore** [comment]
Great, thanks. Interesting reading :D
